sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t skbalasu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true skbalasu/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-849424037203'
  bucket_path: 'docker'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_kEy
  secret_access_key: "$AWS_SECRET_KEY"